### ISSUE TITLE
Issue 10 is not a duplicate of issue 2, please reopen or closed with fix or won't fix reason. 

### ISSUE THREAD

**Issue by u03c1** [sgrigson/oliphant#12] opened 2023-01-22 12:19 UTC
Issue 10 about mamot.fr is not solved by issue #2. 

Issue 2 about fedi.pawlicker.com was closed as fixed by a refactoring and manual removal of the site from your own blocklist.

Issue 10 is about mamot.fr, no reason or fix was provided, no one can explain the presence of this website on the rage.love except a "because we feel it should be", the rage.love website is not giving any reason on his own so we can't argue in favor or reinstatement, no arguments were presented about your own choice on this list as a trusted source.

As a remember, mamot.fr is own by a legal association in France, "La quadrature du Net" fighting for Privacy, Free speech, censorship, engaging in FOSS trial against UE or government. To sum up, this is an organization who is fighting in favor of the fediverse and freesoftware. See https://www.laquadrature.net/en/ for some English publication.

So what reason or legit proof that the whole  mamot.fr instance should be silenced forever can you give ? How do you proceed to certified that a "Trusted source" is to be trusted, appart from "our own feeling" without any document we can refer to see proof of misbehavior of an instance ?
 
If you just doesn't want to give a reason because you don't care about the checking process of any of the blocklist you provide, it's your right, but at least be honest to say it.

If you think that as an admin (or a group of admin), your judgment or process can't be questionable, and you don't have to provide argumented reason to silenced a domain that is fighting against censorship, I would say that "Trusted source" is here the same bullshit than saying "Democratic People's Republic of Korea" to talk about dictatorship.

**Comment by tyrosinase** [comment] 2023-01-22 16:41
If you can convince rage love to remove the block, all your problems will be solved.

(Well, probably not all. You sound like you have a few more.)

**Comment by sgrigson** [comment] 2023-01-22 16:45
1. Nothing needs to be forever, not even federation decisions. Domain names drop off the list all the time.
2. I don't block mamot.fr, so I don't know why you're yelling at me. You can't get mamot.fr off the blocklist by yelling at me.
3. As has been mentioned, this comes from the rage.love list, which I include as a trusted source for blocks.
4. Blocks are available without editorial or reason. The reason is sometimes available on the source site. When a block is removed, I pull in the update, and it will no longer be on the list.

That's how blocks get removed.

This is a duplicate of #11

**Closed by sgrigson** 2023-01-22 16:45 UTC
